title: "K3vzz"
tagline: "AppSec Engineer"
description: "This is my personal portfolio"
github_username: K3vzzWasTaken
baseurl: "/"
url: "https://k3vzz.com"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
remote_theme: "tareqdandachi/jekyll-shell-theme"
