title: "Bili"
tagline: "Computer Engineer"
description: "This is my personal portfolio"
github_username: bilitools
baseurl: "/"
url: ""

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:


# set the size of the text to 'large' or 'small', default is small
font-size: small
remote_theme: "tareqdandachi/jekyll-shell-theme"
